#16 Update code to be compatible with VSF 1.11+
Vendic/vsf-external-checkout pull request #17
Opened 2019-09-27 10:59 UTC by cewald

This is related to #16.

Maybe it should be a new branch or been tagged to let the old version be still available for users using VSF 1.10-.

2019-09-30 10:40 UTC, glevhen requested changes

2019-09-30 10:40 UTC, glevhen commented on README.md
> +import { ExternalCheckout } from 'external-checkout'
@cewald please restore previous module path value, should be
`import { ExternalCheckout } from './external-checkout'`
path `'external-checkout'` is incorrect and will cause error during installation process

2019-09-30 10:40 UTC, glevhen commented on index.ts
> +export const ExternalCheckout: StorefrontModule = function (app, store, router, moduleConfig, appConfig) {
@cewald pass  all parameters to registerModule as one object, so replace this line by
`export const ExternalCheckout: StorefrontModule = function ({app, store, router, moduleConfig, appConfig}) {`

2019-11-01 07:43 UTC, Tjitse-E commented
@cewald can you change your PR so we can merge this?

2019-11-02 09:37 UTC, cewald commented
Done :) Sorry for the massive delay.

2019-11-04 10:24 UTC, glevhen approved these changes

2019-11-04 10:26 UTC, merged